name: reuse

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: "name"
        
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: ${{ inputs.name }}
  output-it:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}
    
  
